# Generated by Django 3.0.7 on 2020-06-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
            ],
            options={
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Locate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_locate', models.CharField(max_length=50)),
                ('us_locate', models.CharField(max_length=50)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudioGhibliApi.Category')),
            ],
            options={
                'verbose_name': 'locate',
            },
        ),
    ]
