# Generated by Django 3.0.7 on 2020-06-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Имена и название фильмов на русском',
                'verbose_name_plural': 'Имена и название фильмов на русском',
            },
        ),
    ]
