# Generated by Django 3.0.7 on 2020-06-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudioGhibliApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locate',
            old_name='id_category',
            new_name='category',
        ),
    ]
